<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExpertExercisesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('exercises')->insert([
            [
                'name' => 'Burpees (Max Effort)',
                'description' => 'A high-intensity full-body movement performed for maximum repetitions or speed.',
                'category' => 'cardio',
                'difficulty' => 'expert',
                'equipment' => 'none',
                'instructions' => 'Drop into a squat, kick feet back, perform a push-up, return to squat, and jump with hands overhead.',
                'video_url' => 'https://www.youtube.com/watch?v=TU8QYVW0gDU',
                'img_url' => 'images/exercises/burpees.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Pull-Ups (Weighted)',
                'description' => 'Strengthens upper back and arms with added resistance.',
                'category' => 'strength',
                'difficulty' => 'expert',
                'equipment' => 'pull-up bar, weight belt/vest',
                'instructions' => 'Attach weight to a belt or vest, grab the bar with an overhand grip, and pull your chin above the bar.',
                'video_url' => 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
                'img_url' => 'images/exercises/weighted_pullups.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Pistol Squat',
                'description' => 'A challenging unilateral leg exercise requiring significant balance, mobility, and strength.',
                'category' => 'strength',
                'difficulty' => 'expert',
                'equipment' => 'none',
                'instructions' => 'Stand on one leg, extending the other leg straight out. Squat down until the working leg is parallel to the ground, then stand back up.',
                'video_url' => 'https://www.youtube.com/watch?v=n6cQhNf-t5k',
                'img_url' => 'images/exercises/pistol_squat.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Handstand Push-Ups',
                'description' => 'A high-level shoulder and triceps strength movement.',
                'category' => 'strength',
                'difficulty' => 'expert',
                'equipment' => 'wall or parallettes',
                'instructions' => 'Kick up into a handstand against a wall. Lower your head towards the floor by bending your elbows, then press back up.',
                'video_url' => 'https://www.youtube.com/watch?v=1F_Xn3jW4iA',
                'img_url' => 'images/exercises/handstand_pushups.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Muscle-Up (Bar)',
                'description' => 'An explosive movement combining a pull-up and a dip.',
                'category' => 'strength',
                'difficulty' => 'expert',
                'equipment' => 'pull-up bar',
                'instructions' => 'Perform an explosive pull-up, transitioning your body over the bar to finish in a dip position, then lower down.',
                'video_url' => 'https://www.youtube.com/watch?v=J8C-Y7d_oJk',
                'img_url' => 'images/exercises/bar_muscle_up.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Clean and Jerk',
                'description' => 'A full-body Olympic lift that develops explosive power and coordination.',
                'category' => 'weightlifting',
                'difficulty' => 'expert',
                'equipment' => 'barbell, weight plates',
                'instructions' => 'Lift the barbell to the shoulders (clean), then lift it overhead (jerk) in one continuous movement.',
                'video_url' => 'https://www.youtube.com/watch?v=t5J539H_8Jk',
                'img_url' => 'images/exercises/clean_and_jerk.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Snatch',
                'description' => 'An explosive Olympic lift where the bar is lifted from the floor to an overhead position in one motion.',
                'category' => 'weightlifting',
                'difficulty' => 'expert',
                'equipment' => 'barbell, weight plates',
                'instructions' => 'Lift the barbell from the floor to a locked-out overhead position in one continuous, powerful motion.',
                'video_url' => 'https://www.youtube.com/watch?v=n9N2H40q6s8',
                'img_url' => 'images/exercises/snatch.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Front Squat',
                'description' => 'A variation of the squat emphasizing core stability and quad development.',
                'category' => 'strength',
                'difficulty' => 'expert',
                'equipment' => 'barbell',
                'instructions' => 'Hold the barbell across the front of your shoulders. Squat down deep while maintaining an upright torso, then stand back up.',
                'video_url' => 'https://www.youtube.com/watch?v=7h2Y-8z147M',
                'img_url' => 'images/exercises/front_squat.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dragon Flag',
                'description' => 'One of the most difficult core exercises for total abdominal and hip flexor strength.',
                'category' => 'core',
                'difficulty' => 'expert',
                'equipment' => 'bench or anchor point',
                'instructions' => 'Grip an anchor behind your head. Lift your entire body (shoulders to feet) into a straight line, then slowly lower the body while maintaining rigidity.',
                'video_url' => 'https://www.youtube.com/watch?v=mjG7sE9R8dY',
                'img_url' => 'images/exercises/dragon_flag.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'L-Sit',
                'description' => 'An isometric core and upper body strength movement.',
                'category' => 'core',
                'difficulty' => 'expert',
                'equipment' => 'parallettes or dip bars',
                'instructions' => 'Support yourself on two parallel bars, keeping your legs straight and extended horizontally in front of you. Hold the position.',
                'video_url' => 'https://www.youtube.com/watch?v=q6g4Uq5l2O0',
                'img_url' => 'images/exercises/lsit.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Kettlebell Snatch',
                'description' => 'A highly technical and explosive movement for total body conditioning.',
                'category' => 'weightlifting',
                'difficulty' => 'expert',
                'equipment' => 'kettlebell',
                'instructions' => 'Swing the kettlebell between your legs and pull it explosively upward, punching your hand through the handle to finish overhead in a locked-out position.',
                'video_url' => 'https://www.youtube.com/watch?v=b4b2X2j4d_Q',
                'img_url' => 'images/exercises/kettlebell_snatch.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Plyometric Push-Ups (Clapping)',
                'description' => 'Develops explosive pushing power in the chest and triceps.',
                'category' => 'plyometrics',
                'difficulty' => 'expert',
                'equipment' => 'none',
                'instructions' => 'Perform a push-up explosively, pushing off the floor hard enough to lift your hands and clap them together before landing softly.',
                'video_url' => 'https://www.youtube.com/watch?v=9j-Gk0zR7Bw',
                'img_url' => 'images/exercises/clapping_pushups.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Turkish Get-Up',
                'description' => 'A complex, multi-stage movement that builds whole-body stability, core strength, and mobility.',
                'category' => 'functional',
                'difficulty' => 'expert',
                'equipment' => 'kettlebell or dumbbell',
                'instructions' => 'Start lying down, holding a weight locked overhead. Stand up while keeping the weight overhead, and then reverse the motion back to the floor.',
                'video_url' => 'https://www.youtube.com/watch?v=oVbYt9h3N-o',
                'img_url' => 'images/exercises/turkish_get_up.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Single-Arm Dumbbell Thruster',
                'description' => 'A high-intensity, compound movement combining a front squat and an overhead press.',
                'category' => 'strength',
                'difficulty' => 'expert',
                'equipment' => 'dumbbell',
                'instructions' => 'Hold a dumbbell at your shoulder. Squat down, and use the upward momentum of the squat to press the dumbbell overhead with one arm.',
                'video_url' => 'https://www.youtube.com/watch?v=b9l1kY54K_I',
                'img_url' => 'images/exercises/single_arm_thruster.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Weighted Dips',
                'description' => 'A powerful exercise for the chest, shoulders, and triceps with added resistance.',
                'category' => 'strength',
                'difficulty' => 'expert',
                'equipment' => 'dip bars, weight belt',
                'instructions' => 'Attach a weight to a belt, grasp the bars, and lower your body until your shoulders are below your elbows, then press back up.',
                'video_url' => 'https://www.youtube.com/watch?v=yY1D9Yy0S9w',
                'img_url' => 'images/exercises/weighted_dips.jpg',
                'is_active' => true,
            ],
        ]);
    }
}